sudo: required
language: python
python:
  - "2.7"

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

before_install:
  - mysql_upgrade --force
  - mysql < Scripts/Build/database/travis-db-setup.sql

install:
  - pip install -r requirements.txt
  - ./Scripts/Build/install/icat.sh
  - ./Scripts/Build/install/activemq.sh

script:
  # ================== Test setup ==================== #
  - ./Scripts/Build/project/migrate_test_settings.sh
  - ./Scripts/Build/database/generate_testing_database.sh
  - mysql < Scripts/Build/database/populate-reduction_viewer-db.sql

  # ================ Assert Test Setup =============== #
  - nosetests Scripts/Build/tests/test_db_generation.py

  # ================ Static Analysis ================= #
  - ./Scripts/Build/tests/test_pylint.sh

  # ================ Nose unit tests ================ #

  # Utils tests
  - nosetests utils/clients/tests
