sudo: required
language: python
python:
  - "2.7"

services:
  - mysql

dist: trusty

before_install:
  - mysql_upgrade --force
  - sudo service mysql restart
  - mysql < build/database/test_db_setup.sql

install:
  # Install autoreduction
  - pip install -e .
  # Install test suite dependencies
  - pip install -r requirements.txt

  # ================== Test setup ==================== #
  - python setup.py test_settings
  # Externals must be after test_settings
  - python setup.py externals -s activemq,icat
  - python setup.py database
  - sudo python setup.py start

script:
  # ================ Assert Test Setup =============== #
  - pytest build/tests/test_db_generation.py

  # ================ Static Analysis ================= #
  - ./build/tests/test_pylint.sh

  # ================ Nose unit tests ================ #

  # Utils tests
  - echo " ================================== TESTS ============================================== "
  - echo "Running Unit tests"
  - py.test --ignore=systemtests --cov=build --cov=monitors --cov=QueueProcessors --cov=scripts --cov=utils --cov=WebApp/autoreduce_webapp --cov=docker_reduction

  - echo "Running System Tests"
  - py.test systemtests --cov-append


after_success:
  - coveralls
