language: python
python:
  - "2.7"

services:
  - mysql

before_install:
  - mysql < Scripts/Build/travis-db-setup.sql

install:
  # ========== Project dependecies ========== #
  - pip install django
  - pip install django_user_agents
  - pip install mysql-python
  - pip install requests
  - pip install stomp.py
  - pip install suds
  - pip install SQLAlchemy
  # === ICAT === #
  - wget https://icatproject.org/misc/python-icat/download/python-icat-0.13.1.tar.gz
  - sudo tar xvf python-icat-0.13.1.tar.gz
  - cd python-icat-0.13.1
  - py_path=$(which python)
  - sudo $py_path setup.py build
  - sudo $py_path setup.py install
  - cd ..
  # ======== Analysis/Testing tools ========= #
  - pip install pylint
  - pip install nose

# command to run tests
script:
  # Create the reduction database on local host
  - mv WebApp/autoreduce_webapp/autoreduce_webapp/test_settings.py WebApp/autoreduce_webapp/autoreduce_webapp/settings.py
  - python WebApp/autoreduce_webapp/manage.py makemigrations reduction_viewer
  - python WebApp/autoreduce_webapp/manage.py migrate reduction_viewer
  # Test successful table migration
  - nosetests Scripts/Build/test/test_db_generation.py
