language: python
python:
  - "2.7"

services:
  - mysql

install:
  # ========== Project dependecies ========== #
  - pip install django
  - pip install django_user_agents
  - pip install mysql-python
  - pip install requests
  - pip install stomp.py
  - pip install suds
  - pip install SQLAlchemy
  # === ICAT === #
  - wget https://icatproject.org/misc/python-icat/download/python-icat-0.13.1.tar.gz
  - sudo tar xvf python-icat-0.13.1.tar.gz
  - cd python-icat-0.13.1
  - py_path=$(which python)
  - sudo $py_path setup.py build
  - sudo $py_path setup.py install
  - cd ..
  # ======== Analysis/Testing tools ========= #
  - pip install pylint
  - pip install nose

# command to run tests
script:
  # Generate the test database for reduction_viewer
  - sudo Scripts/Build/./generate-test-db.sh
  # Test successful table migration
  - nosetests Scripts/Build/test/test_db_generation.py

  # Move EndOfRunMonitor test_settings.py
  - mv EndOfRunMonitor/test_settings.py EndOfRunMonitor/settings.py
  # Test EndOfRunMonitor
  - nosetests EndOfRunMonitor/tests
