language: python
python:
  - "2.7"

services:
  - mysql

install:
  # ========== Project dependencies ========== #
  - pip install django
  - pip install django_user_agents
  - pip install mysql-python
  - pip install python-daemon
  - pip install requests
  - pip install stomp.py
  - pip install suds
  - pip install SQLAlchemy
  - pip install watchdog
  - pip install Twisted==14.0.2
  # ====== ICAT ======= #
  - wget https://icatproject.org/misc/python-icat/download/python-icat-0.13.1.tar.gz
  - sudo tar xvf python-icat-0.13.1.tar.gz
  - cd python-icat-0.13.1
  - py_path=$(which python)
  - sudo $py_path setup.py build
  - sudo $py_path setup.py install
  - cd ..
  # ==== ActiveMQ ===== #
  - wget "http://www.apache.org/dyn/closer.cgi?filename=/activemq/5.15.3/apache-activemq-5.15.3-bin.tar.gz&action=download" -O apache-activemq-5.15.3-bin.tar.gz
  - sudo tar xvf apache-activemq-5.15.3-bin.tar.gz
  - sudo chmod 755 apache-activemq-5.15.3/bin/activemq
  - sudo ./apache-activemq-5.15.3/bin/activemq start
  # Sleep required to give the service time to initialise
  - sleep 5
  # ======== Analysis/Testing tools ========= #
  - pip install pylint
  - pip install nose


script:
  # ========== Test setup ============ #
  # Currently not testing the Scripts/ActiveMQTests - yet to implement assertions for functionality
  - mv Scripts/ActiveMQTests/test_settings.py Scripts/ActiveMQTests/settings.py

  # =============db generation=============== #
  # Create the reduction database on local host
  - mv WebApp/autoreduce_webapp/autoreduce_webapp/test_settings.py WebApp/autoreduce_webapp/autoreduce_webapp/settings.py
  - python WebApp/autoreduce_webapp/manage.py makemigrations reduction_viewer
  - python WebApp/autoreduce_webapp/manage.py migrate reduction_viewer
  # populate database
  - sudo Scripts/Build/./generate-test-db.sh

  # ============ Nose unit tests ============== #
  # MySql
  - nosetests Scripts/Build/test/test_db_generation.py
  # ActiveMQ
  - nosetests Scripts/Build/test/test_activemq_connection.py
  
  # ============= Pylint ============= #
  # Run pylint without check for C0103 (invalid-name) as this triggers on module names
  # There is currently no work around for this - we should change module names to lower case
  - pylint -d C0103 EndOfRunMonitor

  - pylint -d C0103 Scripts/ActiveMQTests/send_message.py
  - pylint -d C0103 Scripts/ActiveMQTests/test_stomp_activemq.py
  - pylint -d C0103 Scripts/ManualSubmissionScript
  - pylint -d C0103 Scripts/NagiosChecks/autoreduce_checklastrun.py

  - pylint -d C0103,W0403,W0141,R0401,C0413 QueueProcessors/QueueProcessor
  - pylint -d C0103,W0403 QueueProcessors/AutoreductionProcessor
  - pylint -d C0103 WebApp/autoreduce_webapp/autoreduce_webapp/
