sudo: required
language: python
python:
  - "2.7"

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

before_install:
  - mysql_upgrade --force
  - sudo service mysql restart
  - mysql < build/database/test_db_setup.sql

install:
  - python setup.py install
  - pip install -r requirements.txt
  
  # ================== Test setup ==================== #
  - python setup.py test_settings
  # Externals must be after test_settings
  - python setup.py externals -s activemq,icat
  - python setup.py database
  - sudo python setup.py start

script:
  # ================ Assert Test Setup =============== #
  - pytest build/tests/test_db_generation.py

  # ================ Static Analysis ================= #
  - ./build/tests/test_pylint.sh

  # ================ Nose unit tests ================ #

  # Utils tests
  - pytest --ignore=scripts --cov=build --cov=QueueProcessors --cov=utils --cov=WebApp/autoreduce_webapp --cov=scripts

after_success:
  - coveralls
