sudo: required
language: python
python:
  - "3.7"

services:
  - mysql

dist: xenial

before_install:
  - mysql_upgrade --force
  - sudo service mysql restart
  - mysql < build/database/test_db_setup.sql

install:
  # Install autoreduction
  - pip3 install -e .
  # Install test suite dependencies
  - pip3 install -r requirements.txt

  # ================== Test setup ==================== #
  - python3 setup.py test_settings
  # Externals must be after test_settings
  - python3 setup.py externals -s activemq,icat
  - python3 setup.py database
  - sudo python3 setup.py start

script:
  # ================ Assert Test Setup =============== #
  - pytest build/tests/test_db_generation.py

  # ================ Static Analysis ================= #
  # ToDo: These should all be collapsed into one once autoreduction gets a single code package
  - pylint build
  - pylint docker_reduction
  - pylint monitors
  - pylint queue_processors
  - pylint scripts
  - pylint systemtests
  - pylint utils

  # ================ pytest unit tests ================ #
  # Utils tests
  - echo "Running Unit tests"
  - py.test --ignore=systemtests --cov=build --cov=monitors --cov=QueueProcessors --cov=scripts --cov=utils --cov=WebApp/autoreduce_webapp --cov=docker_reduction --cov=paths

  - echo "Running System Tests"
  - py.test systemtests --cov-append


after_success:
  - coveralls
