---

- name: Set run_command depending on deployment stage
  include_vars: "{{ deployment_stage }}.yml"

- name: Pull the docker container to get any updates
  become: yes
  command: docker pull ghcr.io/isisscientificcomputing/autoreduce:latest

- name: Start the detached Docker container
  become: yes
  command: docker run {{ run_command }} ghcr.io/isisscientificcomputing/autoreduce:latest
