name: "Deploy Queue Processor"
on:
  workflow_dispatch: # Allows workflow to be triggered manually

jobs:
  build-and-push-qp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H%M')"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: container/qp_py38.Dockerfile
          push: true
          tags: |
            ghcr.io/autoreduction/autoreduce:latest
            ghcr.io/autoreduction/autoreduce:${{ steps.date.outputs.date }}
          cache-from: type=registry,ref=ghcr.io/autoreduction/autoreduce:latest
          cache-to: type=inline
