name: "Deploy runner"
on:
  workflow_dispatch: # Allows workflow to be triggered manually

  schedule:
    - cron: "0 9 * * 0" # every Sunday at 9:00am

jobs:
  build-and-push-nightly:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        deployment: [nightly, latest]
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H%M')"

      - name: Set build args
        id: build_args
        run: |
          if [ ${{ matrix.deployment }} != 'nightly' ]; then
            echo "::set-output name=build_arg::False"
            echo "build-arg set for Latest"
          else
            echo "::set-output name=build_arg::True"
            echo "build-arg set for Nightly"
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: container/runner_py38_mantid.Dockerfile
          build-args: NIGHTLY=${{ steps.build_args.outputs.build_arg }}
          push: true
          tags: |
            ghcr.io/autoreduction/runner-mantid:${{ matrix.deployment }}
            ghcr.io/autoreduction/runner-mantid:${{ steps.date.outputs.date }}-${{ matrix.deployment }}
          cache-from: type=registry,ref=ghcr.io/autoreduction/runner-mantid:${{ matrix.deployment }}
          cache-to: type=inline