name: Tests
on: [push]

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: ./.github/actions/build-autoreduction

      - name: YAPF
        run: python -m yapf --exclude '**/migrations' --parallel --diff --recursive .

      - name: Run unit tests
        run: >-
          pytest --ignore=systemtests --cov=build --cov=monitors --cov=queue_processors
          --cov=scripts --cov=utils --cov=WebApp/autoreduce_webapp --cov=docker_reduction
          --cov=paths --cov=plotting --cov=model --ignore=WebApp/autoreduce_webapp/selenium_tests/

      - name: Run system tests
        run: |
          pytest systemtests --cov-append

      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github

  selenium:
    name: Selenium
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: ./.github/actions/build-autoreduction

      - name: Set up chromedriver
        run: |
          wget https://chromedriver.storage.googleapis.com/87.0.4280.20/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          export PATH=$PATH:./chromedriver_linux64/

      - name: Install chrome
        run: sudo apt-get install -y google-chrome-stable

      - name: Run tests
        run: |
          mv WebApp/autoreduce_webapp/selenium_tests/config.json.example WebApp/autoreduce_webapp/selenium_tests/config.json
          cd WebApp/autoreduce_webapp
          pytest selenium_tests -n 1 --ds=autoreduce_webapp.settings

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: screenshots
          path: WebApp/autoreduce_webapp/selenium_tests/screenshots

  pylint:
    name: Pylint
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: test-user
          MYSQL_PASSWORD: pass
          MYSQL_DATABASE: autoreduction
        ports:
          - '3306:3306'
        options: >-
          --health-cmd="mysqladmin ping" --health-interval=10s
          --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: ./.github/actions/build-autoreduction

      - name: Pylint tests
        run: |
          pylint build
          pylint docker_reduction
          pylint model
          pylint monitors
          pylint queue_processors
          pylint scripts
          pylint systemtests
          pylint utils
          pylint plotting
          pylint webtests
